### PR TITLE
add header

### LINKED ISSUE #7: 1. site navigation
## 1. site navigation 

> assigned to Nadia

__As a site visitor, I want to navigate easily across the website__

### Repository

- [x] developed on a branch called `header`

### HTML

- [x] page title
- [x] link to the font-awesome file
- [x] header element with a class
- [x] nav element with an id as a button menu
- [x] button menu icons
- [x] footer element as an image

### CSS

- [x] header style
- [x] header list items
- [x] header icons and pseudo class
- [x] header nav bar
- [x] footer layout style
- [x] footer image style
- [x] class for hiding labels of the element

### PR DESCRIPTION
**Pull request by ms-np**
update Dev strategy with relevant US;
update index file new element;
update css file with new element rules;
update repo folders;
closes #7 .

### CODE REVIEW

**Review by aleks2407 — CHANGES_REQUESTED** [review]
@ms-np Nadia, I see that parts of your **code are placed in a comment**. Could you please fix that? 
And **the photo** of the footer is **not added** to the folder "images". 
One more moment: me personally would add the footer in other step OR rename the branch to **"header-footer"** for example to make the name of the branch more pronounce. But that's just my personal point of view.

**Comment by ms-np** [comment]
@aleks2407 I'll make another commit and push it again so that make sure all the newly added files including the footer image have been included. Let's see how it will affect the page preview.

**Comment by ms-np** [comment]
however, the comments don't affect the code as far as I know (just as comments like Global or Section don't affect the code), right?

**Comment by ms-np** [comment]
And the name of the branch is the internal development process naming  and as far as it doesn't affect the end-user or it doesn't falls out of the internal conventions, I'll try to make it as short as possible so that it's handy to use with Terminal/CL.

**Comment by aleks2407** [comment]
Now it looks good to me! thanks!

**Pull request merged**
