### PR TITLE
add feature section

### LINKED ISSUE #9: 3. features
## 3. features

> assigned to Nadia

__As a site visitor, I want to learn more about the product features of the company__

### Repository

- [x] developed on a branch called `features`

### HTML

- [x] A section element with an id
- [x] Heading and paragraphs element
- [x] List element
- [x] Form element
- [x] Link element

### CSS

- [x] features section layout
- [x] heading and paragraph layout and styling
- [x] list items layout
- [x] icon style
- [x] link layout and style
- [x] button style

### PR DESCRIPTION
**Pull request by ms-np**
add new section to index file
add new rules for this section to css file
update dev strategy with relevant US;
closes #9

### CODE REVIEW

**Comment by ms-np** [comment]
Hi! In addition to the new section, I've checked how to get rid of the huge extra-space between Feature block and Boxes block and here's what I did manage to try locally: 
  http://prntscr.com/sypfgd (getting rid of the extra space)
  
  http://prntscr.com/sypf44 (the margin that has been refined).

My offer is that I include this refinement into my "Final touches" (unless you wanna make this change yourself, of course). 
Lemme know if it's okey with you.

**Review by aleks2407 — CHANGES_REQUESTED** [review]
Nadia, yes, that's right)))now I remember it, I left that space to imagine how it would look visually while your section wasn't there yet)) You did a great job on this section
I would suggest that you include this margin correction in this step, so website looks better directly. 

For the half-full star check this , maybe it will be useful :) https://www.w3schools.com/icons/tryit.asp?filename=tryicons_fa-star-half-full

**Privacy Protection For Any Device** - This shouldn't be BOLD , i think.

**Comment by ms-np** [comment]
Hey!
1 - Okey, I'll handle the margin with a new commit.

2 - I've tried to play around with fonts and weights but it seems that the problem is with font family itself. Tell me what do you think and if it looks okey? 
   2.1. Without bold font - https://prnt.sc/t0b08z 
   2.2. Current merge version - https://prnt.sc/t0b4ja

Personally, I don't feel like (2.1) fits in.

**Comment by ms-np** [comment]
Nice idea with a star :thumbsup:
Maybe next time as I don't feel like bothering with external fa-icons now rather than find out something new about built-in elements styling as this one ==> ★ .

**Review by aleks2407 — APPROVED** [review]

**Pull request merged**
